
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int number = 17;
  public static final int minus = 5;
  public static final int coma = 13;
  public static final int vector_variable = 16;
  public static final int semicolon = 8;
  public static final int power = 3;
  public static final int scalar_variable = 15;
  public static final int multiply = 6;
  public static final int divide = 7;
  public static final int left_square_bracket = 10;
  public static final int EOF = 0;
  public static final int equal = 9;
  public static final int exponent = 2;
  public static final int dot = 14;
  public static final int question_mark = 12;
  public static final int error = 1;
  public static final int right_square_bracket = 11;
  public static final int plus = 4;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "exponent",
  "power",
  "plus",
  "minus",
  "multiply",
  "divide",
  "semicolon",
  "equal",
  "left_square_bracket",
  "right_square_bracket",
  "question_mark",
  "coma",
  "dot",
  "scalar_variable",
  "vector_variable",
  "number"
  };
}

